########################################################################################################################
# Repo tool base settings
########################################################################################################################

[repo]

# Repository Name
name = "warp"

extra_tool_paths = [
    "${root}/_build/kit-deps/kit-kernel/dev",
]

import_configs = [
    "${root}/_repo/deps/repo_kit_tools/kit-template/repo.toml",
]


########################################################################################################################
# Build tool setup
########################################################################################################################

[repo_build]

# List of packman projects to pull (in order)
fetch.packman_host_files_to_pull = [
    "${root}/deps/host-deps.packman.xml",
]

fetch.packman_target_files_to_pull = [
    "${root}/deps/target-deps.packman.xml",
]

# Extensions precache
fetch.after_pull_commands = [
]

[repo_build_number]
enabled = true

########################################################################################################################
# Extensions publisher
########################################################################################################################

[repo_publish_exts]

kit_path = "${root}/_build/kit-deps/kit-kernel/kit${exe_ext}"

ext_folders = [
    "${root}/_build/${platform_target}/${config}/exts"
]

exts.include = [
    "omni.warp",
    "omni.warp.core",
]

configs = ["release"]
platforms = ["windows-x86_64", "linux-x86_64"]
