[package]
# Semantic Versioning is used: https://semver.org/
version = "1.6.2"
authors = ["NVIDIA"]
title = "Warp Core"
description="The core Warp Python module"
readme  = "docs/README.md"
repository="https://github.com/nvidia/warp"
category = "core"
keywords = ["warp", "simulation"]
changelog="docs/CHANGELOG.md"
writeTarget.platform = true
support_level = "Enterprise"

preview_image = "data/preview.png"
icon = "data/icon.png"

# Watch files for hot reloading (only works for Python files)
[fswatcher.patterns]
include = ["*.py"]

[dependencies]
"omni.kit.pip_archive" = {}

# Extension module
# It must be defined before the module `warp` in order to give
# the `omni.warp.core` extension a chance to create a symlink towards Warp's
# core directory, if needed, before Carbonite tries to evaluate `import warp`.
[[python.module]]
name = "omni.warp.core"

# Core language module
[[python.module]]
name = "warp"
path = "."
public = true

# Kit testing flags
[[test]]
pyCoverageOmit = [
    "warp/examples/**",
    "warp/fem/**",
    "warp/optim/**",
    "warp/render/**",
    "warp/sim/**",
    "warp/tests/**",
    "warp/thirdparty/**",
    "warp/build_dll.py",
    "warp/dlpack.py",
    "warp/jax.py",
    "warp/jax_experimental.py",
    "warp/paddle.py",
    "warp/stubs.py",
    "warp/torch.py",
]
timeout = 900
